services:
  server:
    build:
      context: .
    ports:
      - 5000:5000
    networks:
      - app-tier
  
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
