apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: TestApp
  template:
    metadata:
      labels:
        app: TestApp
    spec:
      containers:
        - name: hello-app-container
          image: leonardobenitez/test-app:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
